// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFinancialControl.Server.Data;

#nullable disable

namespace MyFinancialControl.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyFinancialControl.Server.Models.ExpenseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Payer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c25b6670-897d-46b3-ad97-bb685552d6dc"),
                            Date = new DateTime(2023, 10, 31, 10, 44, 26, 293, DateTimeKind.Local).AddTicks(9131),
                            Name = "Conta de luz",
                            Payer = "Roberto",
                            TagName = "Conta de luz",
                            Value = 270.0
                        },
                        new
                        {
                            Id = new Guid("0fbd3b02-6d29-40ed-aaaf-070f43f9be4e"),
                            Date = new DateTime(2023, 10, 31, 10, 44, 26, 293, DateTimeKind.Local).AddTicks(9146),
                            Name = "Madrid",
                            Payer = "Roberto",
                            TagName = "Mercado",
                            Value = 300.0
                        },
                        new
                        {
                            Id = new Guid("d7cde773-85a0-46a6-a39a-ad7f65a7033c"),
                            Date = new DateTime(2023, 10, 31, 10, 44, 26, 293, DateTimeKind.Local).AddTicks(9148),
                            Name = "Padaria",
                            Payer = "Roberto",
                            TagName = "Alimentação",
                            Value = 40.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
